# Generated by Django 4.0.2 on 2022-06-03 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_genre_alter_genre_title_alter_user_book'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserList',
        ),
    ]
