# Generated by Django 4.0.2 on 2022-06-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_user_userlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlist',
            name='rate',
        ),
        migrations.AddField(
            model_name='userlist',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
