# Generated by Django 4.0.2 on 2022-06-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_userlist_rate_userlist_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topten',
            name='title',
            field=models.CharField(max_length=64),
        ),
    ]
